### Register User
POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "your-username",
    "password": "your-password"
}

### Login User
POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "isaac",
    "password": "isaac"
}

### Test the session endpoint with the session cookie
GET http://localhost:3001/session
Content-Type: application/json
Cookie: connect.sid=s%3AKzrqJDDN9dTXq4hjBvAVNdz0ddX6CtI-.fbssdF0HOZ%2Fgz8r66ei3aYSj56Qtfcrdlix22wPHgHs

###
GET http://localhost:3001/tasks HTTP/1.1

###

POST http://localhost:3001/task/new
Content-Type: application/json

{
    "text": "Gym"
}

###

DELETE http://localhost:3001/task/delete/66b6bbce764f8764ad38df60

###

GET http://localhost:3001/task/done/60e585d86177f95ff0574323

###

PUT http://localhost:3001/task/update/66b6c2e66f7db28fc2c0476b
Content-Type: application/json

{
    "text": "Gym",
    "year": "2024",
    "month": "08",
    "day": "10"
}